version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/
      - /usr/src/node_modules
    ports:
      - "3000:3000"
    depends_on:
       - postgres

  postgres:
     image: postgres
     environment:
      POSTGRES_USER: "knrt10"
      POSTGRES_PASSWORD: "knrt10"
      POSTGRES_DB: "hasura"
     ports:
       - "5432:5432"
     volumes:
       - ./data:/data/db
